### ISSUE TITLE
The file  TZrules.dat could not be found

### ISSUE THREAD

**Issue by probonopd** [appimage-packages/kstars#1]
On `ubuntu-16.04-desktop-amd64.iso`, `kstars-git12052016-x86_64.AppImagee` gives

```
The file  TZrules.dat could not be found. KStars cannot run properly without this file. KStars searches for this file in following locations:

	/home/me/.local/share/kstars
	/usr/share/ubuntu/kstars
	/usr/share/gnome/kstars
	/usr/local/share/kstars
	/usr/share/kstars
	/var/lib/snapd/desktop/kstars

It appears that your setup is broken.
```

Somewhere there seem to be hardcoded paths to `/usr`. These could be pulled in from KStars itself or, more likely, one of its direct or indirect dependencies.

We should think about how to best solve this class of problems. Recently I have been playing with LD_PRELOAD "overlay filesystems" with some success, https://github.com/probonopd/AppImageKit/issues/267. The advantage is that you don't have to patch away the absolute paths in each package but have a generic solution.

As an alternative, we can binpatch `/usr` to the equally long string `././` and cd to `$APPDIR/usr` before executing the payload app, but that brings with it another set of problems (e.g., breaks as soon as the application tries to `chdir()`).

**Comment by ScarlettGatelyMoore** [comment]
Going with LD_PRELOAD route as kdevelop and peruse use this with success.
Which fixes this issue. Creating new issue with the new fun errors.
