### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by ScarlettGatelyMoore** [appimage-packages/kstars#2]
scarlett@scarlett-maui-desktop:~/Downloads$ ./kstars-git12072016-x86_64.AppImage 
Welcome to KStars 2.7.2
"Setting clock:  UTC: Wed Dec 7 18:55:10 2016 GMT  JD: 2,457,730.29"
Opened the DSO Database. Ready!
Opened the User DB. Ready.
Processing  "unnamedstars.dat" , HTMesh Level 3
  Sky Mesh Size:  512
Loaded DSO catalog file:  "unnamedstars.dat"
"Star HD61421 not found."
"Star HD10700 not found."
"Star HD20794 not found."
"Star HD2151 not found."
"Star HD190248 not found."
"Star HD142860 not found."
"Star HD1581 not found."
"Star HD1581 not found."
"Star HD98230 not found."
File opened:  "/tmp/.mount_E9jSXM/usr/share/kstars/ngcic.dat"
Loading NGC/IC objects
File opened:  "/tmp/.mount_E9jSXM/usr/share/kstars/asteroids.dat"
File opened:  "/tmp/.mount_E9jSXM/usr/share/kstars/comets.dat"
ASSERT: "a && i >= 0 && i < (int)a->length" in file json/qjsonarray.cpp, line 591
KCrash: crashing... crashRecursionCounter = 2
KCrash: Application Name = kstars path = /tmp/.mount_E9jSXM/usr/bin pid = 26762
KCrash: Arguments: /tmp/.mount_E9jSXM/usr/bin/kstars 
KCrash: Attempting to start /usr/lib/x86_64-linux-gnu/libexec/drkonqi from kdeinit
sock_file=/run/user/1000/kdeinit5__0
No WishList Saved yet
"Object named NGC 3314A not found"
QSocketNotifier: Invalid socket 9 and type 'Read', disabling...
QSocketNotifier: Invalid socket 10 and type 'Read', disabling...
Starting the timer

I have a sneaking suspision libindi is too old. Going to try newest version.

**Comment by probonopd** [comment]
On Ubuntu 16.04:

```
me@host:~$ '/home/me/Downloads/kstars-git12072016-x86_64.AppImage' 
kstars: error while loading shared libraries: libKF5Crash.so.5: cannot open shared object file: No such file or directory
```

**Comment by ScarlettGatelyMoore** [comment]
Ahh easy fix, needs kcrash added to deps. Thanks, will add that with libindi

**Comment by ScarlettGatelyMoore** [comment]
hmm no it is there, further investigation required

**Comment by probonopd** [comment]
Might well be a linuxdeployqt/patchelf issue.

**Comment by ScarlettGatelyMoore** [comment]
I am getting closer to resolving this. I think it is my flaw, I now realize linuxdeployqt want the binary in $APP.AppDir/mybinary and I have been copying the full path $APP.AppDir/usr/bin/mybinary I am going to make the adjustments today.

**Comment by ScarlettGatelyMoore** [comment]
Newest error
scarlett@scarlett-maui-desktop:~/Downloads$ ./kstars-git12082016-x86_64.AppImage 
Welcome to KStars 2.7.2
"Setting clock:  UTC: Thu Dec 8 17:31:44 2016 GMT  JD: 2,457,731.23"
Opened the DSO Database. Ready!
Opened the User DB. Ready.
Processing  "unnamedstars.dat" , HTMesh Level 3
  Sky Mesh Size:  512
Loaded DSO catalog file:  "unnamedstars.dat"
"Star HD61421 not found."
"Star HD10700 not found."
"Star HD20794 not found."
"Star HD2151 not found."
"Star HD190248 not found."
"Star HD142860 not found."
"Star HD1581 not found."
"Star HD1581 not found."
"Star HD98230 not found."
File opened:  "/tmp/.mount_pokZhz/usr/share/kstars/ngcic.dat"
Loading NGC/IC objects
File opened:  "/tmp/.mount_pokZhz/usr/share/kstars/asteroids.dat"
File opened:  "/tmp/.mount_pokZhz/usr/share/kstars/comets.dat"
ASSERT: "a && i >= 0 && i < (int)a->length" in file json/qjsonarray.cpp, line 591
/tmp/.mount_pokZhz/AppRun: line 28:  1232 Aborted                 kstars $@

Need to see what they are asserting there.

**Comment by probonopd** [comment]
> linuxdeployqt want the binary in $APP.AppDir/mybinary

Yes. This is what macdeployqt does too, which was the basis for linuxdeployqt. But:

> I have been copying the full path $APP.AppDir/usr/bin/mybinary

I can definitely see cases where this is more desirable on Linux systems. For this I have created the "[FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard)-like mode" in the [feature/fhs](https://github.com/probonopd/linuxdeployqt/tree/feature/fhs) branch which unfortunately suffers from https://github.com/probonopd/linuxdeployqt/issues/47 / https://github.com/NixOS/patchelf/issues/110.

**Comment by ScarlettGatelyMoore** [comment]
fixed

**Comment by probonopd** [comment]
Runs on `xubuntu-16.04-desktop-amd64.iso` (theme looks decidedly non-native), `debian-live-8.0.0-amd64-xfce-desktop+nonfree.iso`, `Fedora-Live-Workstation-x86_64-22-3.iso`, `Fedora-Workstation-Live-x86_64-24-1.2.iso`, `Fedora-Workstation-Live-x86_64-25-20161105.n.0.iso`, `CentOS-7-x86_64-LiveGNOME-1511.iso`,  `CentOS-7.0-1406-x86_64-GnomeLive.iso`,   :+1:

Does __not__ run on `debian_7.0.0_wheezy_i386_20130705_binary.hybrid.iso` (`AppRun: 16: /mnt/AppRun: kstars: not found`).

**Comment by ScarlettGatelyMoore** [comment]
I don't think it will run on any i386... it was built only for amd64

**Comment by probonopd** [comment]
Aaargh, stupid me, sure! So much is clear.
